name: Build and Deploy to Azure Web App via Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_HUB_REPO: rajeshalda/meeting-time-tracker
  AZURE_WEBAPP_NAME: chronopulse
  RESOURCE_GROUP: intervaltime

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create .env.local
      run: |
        cat << EOF > .env.local
        PORT=8080
        AZURE_AD_CLIENT_ID=${{ secrets.AZURE_AD_CLIENT_ID }}
        AZURE_AD_CLIENT_SECRET=${{ secrets.AZURE_AD_CLIENT_SECRET }}
        AZURE_AD_TENANT_ID=${{ secrets.AZURE_AD_TENANT_ID }}
        AZURE_AD_APP_CLIENT_ID=${{ secrets.AZURE_AD_CLIENT_ID }}
        AZURE_AD_APP_CLIENT_SECRET=${{ secrets.AZURE_AD_CLIENT_SECRET }}
        AZURE_AD_APP_TENANT_ID=${{ secrets.AZURE_AD_TENANT_ID }}
        NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
        NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
        AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}
        AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_DEPLOYMENT=${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
        EOF
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_HUB_REPO }}:latest
          ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.DOCKER_HUB_REPO }}:latest
        cache-to: type=inline
        
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group-name: ${{ env.RESOURCE_GROUP }}
        images: ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }} 